fieldLayouts:
  0b12656c-dcff-4dd1-bde5-13018d30376f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b75d7a06-ed08-4b33-acdf-885d6446e9db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 066d6651-9734-4ec3-b8df-e73535178ef7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: df275c3d-7235-4291-828d-4527a56148e4 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
