isPublic: true
name: 'Public Schema'
scope:
  - 'sites.e99faab1-930e-410a-9275-15949843b78d:read' # Craft Headless Nuxt EN
  - 'sites.62b8519f-3e6a-488b-b6b5-0f260e2ae0ca:read' # Craft Headless Nuxt NL
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.ecb05899-738e-41b2-8d85-a74583976e68:read' # Home
  - 'entrytypes.a47da6fb-c5bb-40c6-a49d-661d60068d3f:read' # Home
  - 'sections.df275c3d-7235-4291-828d-4527a56148e4:read' # Pages
  - 'entrytypes.fae35562-c9f0-40db-a725-05f1d859dd69:read' # Default
  - 'entrytypes.aa35744a-858e-4b8b-a532-27c81610a3f6:read' # Contact
  - 'globalsets.85eb887f-057a-4ab2-8c67-e744e202d60c:read' # Navigation
  - 'usergroups.everyone:read'
  - 'categorygroups.dd227703-c864-4a4b-8185-fe18ea0785c3:read' # Projects
