dateModified: 1667244483
email:
  fromEmail: info@angelokeirsebilck.be
  fromName: 'Craft Headless Nuxt'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7beb5529-5b56-4634-9f29-1eb51e3da406: Navigation # Navigation
    7bf5d9f2-b0e8-44eb-bd2a-931ae1610977: Text # Text
    7dcedf78-ee98-48df-a260-81de2f469239: 'Public Schema' # Public Schema
    62b8519f-3e6a-488b-b6b5-0f260e2ae0ca: 'Craft Headless Nuxt NL' # Craft Headless Nuxt NL
    85eb887f-057a-4ab2-8c67-e744e202d60c: Navigation # Navigation
    777bca22-ebba-4f45-8ddf-b45686b71475: 'Private Schema' # Private Schema
    843e693f-2b71-469b-a9e4-4a8085586dbc: 'Craft Headless Nuxt' # Craft Headless Nuxt
    a9acb779-9fef-4035-9867-d89c723f9086: 'Content Builder' # Content Builder
    a47da6fb-c5bb-40c6-a49d-661d60068d3f: Home # Home
    ab6e131b-048e-4a08-9c67-43e9524869b4: Text # Text
    b8251fa3-3bd7-4ffa-a018-6be6a3ff400c: Link # Link
    cf5f6192-c76b-4391-9083-1f98915d31aa: 'Main Navigation' # Main Navigation
    dd227703-c864-4a4b-8185-fe18ea0785c3: Projects # Projects
    df275c3d-7235-4291-828d-4527a56148e4: Pages # Pages
    e99faab1-930e-410a-9275-15949843b78d: 'Craft Headless Nuxt EN' # Craft Headless Nuxt EN
    eb118b96-e8db-471f-9e8f-6ea1a2b1a3fe: Common # Common
    ecb05899-738e-41b2-8d85-a74583976e68: Home # Home
    fae35562-c9f0-40db-a725-05f1d859dd69: Default # Default
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: pro
  live: true
  name: 'Craft Headless Nuxt'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
