defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Nuxt Preview'
      -
        - urlFormat
        - '@nuxtPreviewUrl/{site.language}/{uri}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  62b8519f-3e6a-488b-b6b5-0f260e2ae0ca: # Craft Headless Nuxt NL
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri}/{slug}'
  e99faab1-930e-410a-9275-15949843b78d: # Craft Headless Nuxt EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri}{slug}'
structure:
  maxLevels: null
  uid: a7a931a3-b3c6-436f-bad5-780844d97e2b
type: structure
